export const userActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAIL: 'SIGN_IN_FAIL',
    EMAIL_SIGN_UP_START: 'EMAIL_SIGN_UP_START',
    EMAIL_SIGN_UP_SUCCESS: 'EMAIL_SIGN_UP_SUCCESS',
    EMAIL_SIGN_UP_FAIL: 'EMAIL_SIGN_UP_FAIL'
}